### ISSUE TITLE
Class "Nyholm\Psr7\Uri" not found, when calling years API

### ISSUE THREAD

**Issue by vimalgorasiya** [car-api-team/carapi-php-sdk#4]
Hi,

When I am trying to call `$years = $sdk->years();` I am getting below error.

> Class "Nyholm\Psr7\Uri" not found

In composer.json, I can see its added in `require-dev` block, I am not sure but may be need to place it in `require` block?

Thanks.

**Comment by carapidev** [comment]
The SDK uses https://github.com/php-http/discovery to discover whatever HTTP client your project is using. Can you please post your `composer.json` , the code you used to build the SDK and any other information that may be pertinent to reproduce the issue?

**Comment by vimalgorasiya** [comment]
Here is my `composer.json`

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "car-api-team/carapi-php-sdk": "^1.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}

I just installed SDK using composer with below command

`composer require car-api-team/carapi-php-sdk`

Then called first API `$years = $sdk->years();`

And got the above error.

**Comment by carapidev** [comment]
There indeed seems to be a bug here. To work around this for now you may:

```console
composer require nyholm/psr7
```

We'll need to look into this more to see if there is a way to not require that as a core dependency. We'll keep this open and let you know when its resolved. Thanks.

**Comment by carapidev** [comment]
@vimalgorasiya We replaced this with a factory finder. Should not need to require `nyholm/psr7` as the library will find a concrete Uri class from within your project now. We'll add some additional coverage that tests the library in a non require-dev install here: #6
